# Generated by Django 5.2 on 2026-02-11 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("venue", models.CharField(blank=True, default="", max_length=300)),
                ("website_url", models.URLField(blank=True, default="")),
                ("pretalx_event_slug", models.CharField(blank=True, default="", max_length=200)),
                ("stripe_secret_key", models.CharField(blank=True, default="", max_length=200)),
                ("stripe_publishable_key", models.CharField(blank=True, default="", max_length=200)),
                ("stripe_webhook_secret", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "start_date"],
                "unique_together": {("conference", "slug")},
            },
        ),
    ]
