# Generated by Django 5.2.11 on 2026-02-11 03:03

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="stripe_publishable_key",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="conference",
            name="stripe_secret_key",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="conference",
            name="stripe_webhook_secret",
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
