# Generated by Django 5.2.11 on 2026-02-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0003_conference_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="total_capacity",
            field=models.PositiveIntegerField(
                default=0, help_text="Maximum total tickets across all types. 0 means unlimited."
            ),
        ),
    ]
