# Generated by Django 5.2.11 on 2026-02-14 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0003_conference_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlags",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "registration_enabled",
                    models.BooleanField(
                        blank=True,
                        help_text="Override registration toggle. Leave blank to use default from settings.",
                        null=True,
                    ),
                ),
                ("sponsors_enabled", models.BooleanField(blank=True, help_text="Override sponsors toggle.", null=True)),
                (
                    "travel_grants_enabled",
                    models.BooleanField(blank=True, help_text="Override travel grants toggle.", null=True),
                ),
                (
                    "programs_enabled",
                    models.BooleanField(blank=True, help_text="Override programs/activities toggle.", null=True),
                ),
                (
                    "pretalx_sync_enabled",
                    models.BooleanField(blank=True, help_text="Override Pretalx sync toggle.", null=True),
                ),
                (
                    "public_ui_enabled",
                    models.BooleanField(blank=True, help_text="Override public UI toggle.", null=True),
                ),
                (
                    "manage_ui_enabled",
                    models.BooleanField(blank=True, help_text="Override manage UI toggle.", null=True),
                ),
                ("all_ui_enabled", models.BooleanField(blank=True, help_text="Master UI switch override.", null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature flags",
                "verbose_name_plural": "feature flags",
            },
        ),
    ]
