# Generated by Django 5.2.11 on 2026-02-14 04:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0004_add_feature_flags"),
        ("program_conference", "0004_add_total_capacity"),
    ]

    operations = []
