# Generated by Django 5.2.11 on 2026-03-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0005_merge_0004_add_feature_flags_0004_add_total_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="grant_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="Budget allocated for travel grants.", max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="revenue_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target revenue budget for this conference.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="target_attendance",
            field=models.PositiveIntegerField(blank=True, help_text="Target number of attendees.", null=True),
        ),
    ]
