# Generated by Django 5.2.11 on 2026-03-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0007_expensecategory_expense"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPITargets",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "target_conversion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target cart-to-order conversion rate (%). Industry avg ~3%.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_refund_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum acceptable refund rate (%). Typical target: 5%.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_checkin_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target check-in rate (%). Strong turnout >= 80%.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_fulfillment_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target sponsor benefit fulfillment rate (%). Goal: 90%+.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "target_revenue_per_attendee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target revenue per attendee ($).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "target_room_utilization",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target room utilization rate (%). Industry avg ~28%.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_targets",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI targets",
                "verbose_name_plural": "KPI targets",
            },
        ),
    ]
