# Generated by Django 5.2.11 on 2026-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0008_kpitargets"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflags",
            name="visa_letters_enabled",
            field=models.BooleanField(blank=True, help_text="Override visa invitation letters toggle.", null=True),
        ),
    ]
