# Generated by Django 5.2.11 on 2026-03-19 18:36

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0009_featureflags_visa_letters_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="qbo_access_token",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, default=None, help_text="QBO OAuth2 access token.", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="qbo_client_id",
            field=models.CharField(
                blank=True, default="", help_text="QBO OAuth2 client ID for token refresh.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="qbo_client_secret",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                default=None,
                help_text="QBO OAuth2 client secret for token refresh.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="qbo_realm_id",
            field=models.CharField(
                blank=True, default="", help_text="QuickBooks Online Company/Realm ID.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="qbo_refresh_token",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, default=None, help_text="QBO OAuth2 refresh token.", max_length=2000, null=True
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="qbo_token_expires_at",
            field=models.DateTimeField(blank=True, help_text="When the QBO access token expires.", null=True),
        ),
    ]
