# Generated by Django 5.2.11 on 2026-02-11 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("program_conference", "0002_encrypt_stripe_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pretalx_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=300)),
                ("biography", models.TextField(blank=True, default="")),
                ("avatar_url", models.URLField(blank=True, default="")),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speaker_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("conference", "pretalx_code")},
            },
        ),
        migrations.CreateModel(
            name="Talk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pretalx_code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("submission_type", models.CharField(blank=True, default="", max_length=200)),
                ("track", models.CharField(blank=True, default="", max_length=200)),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
                ("state", models.CharField(blank=True, default="", max_length=50)),
                ("room", models.CharField(blank=True, default="", max_length=200)),
                ("slot_start", models.DateTimeField(blank=True, null=True)),
                ("slot_end", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talks",
                        to="program_conference.conference",
                    ),
                ),
                ("speakers", models.ManyToManyField(blank=True, related_name="talks", to="program_pretalx.speaker")),
            ],
            options={
                "ordering": ["slot_start", "title"],
                "unique_together": {("conference", "pretalx_code")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("room", models.CharField(blank=True, default="", max_length=200)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("talk", "Talk"), ("break", "Break"), ("social", "Social"), ("other", "Other")],
                        max_length=50,
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_slots",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "talk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_slots",
                        to="program_pretalx.talk",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "room"],
            },
        ),
    ]
