# Generated by Django 5.2.11 on 2026-02-11 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0002_encrypt_stripe_fields"),
        ("program_pretalx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pretalx_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
                "unique_together": {("conference", "pretalx_id")},
            },
        ),
        migrations.AlterField(
            model_name="scheduleslot",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_slots",
                to="program_pretalx.room",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="talks",
                to="program_pretalx.room",
            ),
        ),
    ]
