# Generated by Django 5.2.11 on 2026-02-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0002_encrypt_stripe_fields"),
        ("program_pretalx", "0002_room_alter_scheduleslot_room_alter_talk_room"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scheduleslot",
            constraint=models.UniqueConstraint(
                fields=("conference", "start", "room"),
                name="uniq_schedule_slot_conference_start_room",
            ),
        ),
    ]
