# Generated by Django 5.2.11 on 2026-02-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0003_conference_address"),
        ("program_pretalx", "0004_talk_tags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="room",
            name="pretalx_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pretalx_id", None), _negated=True),
                fields=("conference", "pretalx_id"),
                name="unique_room_pretalx_id_per_conference",
            ),
        ),
    ]
