# Generated by Django 5.2.11 on 2026-02-14 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0003_conference_address"),
        ("program_pretalx", "0005_alter_room_unique_together_alter_room_pretalx_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "override_title",
                    models.CharField(blank=True, default="", help_text="Override the talk title.", max_length=500),
                ),
                (
                    "override_state",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Override the talk state (e.g. confirmed, withdrawn).",
                        max_length=50,
                    ),
                ),
                (
                    "override_slot_start",
                    models.DateTimeField(blank=True, help_text="Override the scheduled start time.", null=True),
                ),
                (
                    "override_slot_end",
                    models.DateTimeField(blank=True, help_text="Override the scheduled end time.", null=True),
                ),
                (
                    "override_abstract",
                    models.TextField(blank=True, default="", help_text="Override the talk abstract."),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(
                        default=False, help_text="Mark this talk as cancelled. Overrides the state to 'cancelled'."
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Internal note explaining the reason for this override."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talk_overrides",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_talk_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "override_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override the room assignment for this talk.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="talk_overrides",
                        to="program_pretalx.room",
                    ),
                ),
                (
                    "talk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="override", to="program_pretalx.talk"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionTypeDefault",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "submission_type",
                    models.CharField(
                        help_text="The Pretalx submission type name to match (e.g. 'Poster', 'Tutorial').",
                        max_length=200,
                    ),
                ),
                (
                    "default_date",
                    models.DateField(blank=True, help_text="Default date for talks of this type.", null=True),
                ),
                (
                    "default_start_time",
                    models.TimeField(blank=True, help_text="Default start time for talks of this type.", null=True),
                ),
                (
                    "default_end_time",
                    models.TimeField(blank=True, help_text="Default end time for talks of this type.", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_type_defaults",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "default_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default room for talks of this type.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submission_type_defaults",
                        to="program_pretalx.room",
                    ),
                ),
            ],
            options={
                "ordering": ["submission_type"],
                "unique_together": {("conference", "submission_type")},
            },
        ),
    ]
