# Generated by Django 5.2.11 on 2026-02-14 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0003_conference_address"),
        ("program_pretalx", "0006_talkoverride_submissiontypedefault"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="talkoverride",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="program_conference.conference",
            ),
        ),
        migrations.AlterField(
            model_name="talkoverride",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RoomOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Internal note explaining the reason for this override."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "override_name",
                    models.CharField(blank=True, default="", help_text="Override the room name.", max_length=300),
                ),
                (
                    "override_description",
                    models.TextField(blank=True, default="", help_text="Override the room description."),
                ),
                (
                    "override_capacity",
                    models.PositiveIntegerField(blank=True, help_text="Override the room capacity.", null=True),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="override", to="program_pretalx.room"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeakerOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Internal note explaining the reason for this override."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "override_name",
                    models.CharField(
                        blank=True, default="", help_text="Override the speaker's display name.", max_length=300
                    ),
                ),
                (
                    "override_biography",
                    models.TextField(blank=True, default="", help_text="Override the speaker biography."),
                ),
                (
                    "override_avatar_url",
                    models.URLField(blank=True, default="", help_text="Override the speaker avatar URL."),
                ),
                (
                    "override_email",
                    models.EmailField(
                        blank=True, default="", help_text="Override the speaker contact email.", max_length=254
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "speaker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override",
                        to="program_pretalx.speaker",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "abstract": False,
            },
        ),
    ]
