# Generated by Django 5.2.11 on 2026-02-14 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0005_merge_0004_add_feature_flags_0004_add_total_capacity"),
        ("program_pretalx", "0007_alter_talkoverride_conference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomoverride",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_overrides",
                to="program_conference.conference",
            ),
        ),
        migrations.AlterField(
            model_name="roomoverride",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_room_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="speakeroverride",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speaker_overrides",
                to="program_conference.conference",
            ),
        ),
        migrations.AlterField(
            model_name="speakeroverride",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_speaker_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="talkoverride",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talk_overrides",
                to="program_conference.conference",
            ),
        ),
        migrations.AlterField(
            model_name="talkoverride",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_talk_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
