"""URL configuration for the conference management dashboard.

Mount under a prefix in the host project::

    urlpatterns = [
        path("manage/", include("django_program.manage.urls")),
    ]
"""

from django.urls import include, path

from django_program.manage.views import (
    ActivityCreateView,
    ActivityDashboardExportView,
    ActivityDashboardView,
    ActivityEditView,
    ActivityManageListView,
    ActivityPromoteSignupView,
    AddOnCreateView,
    AddOnEditView,
    AddOnListView,
    AttendeeDetailView,
    AttendeeListView,
    BadgeBulkDownloadView,
    BadgeBulkGenerateView,
    BadgeDownloadView,
    BadgeListView,
    BadgePreviewView,
    BadgeTemplateCreateView,
    BadgeTemplateEditView,
    BadgeTemplateListView,
    ConditionCreateView,
    ConditionEditView,
    ConditionListView,
    ConferenceEditView,
    ConferenceListView,
    DashboardView,
    ExpenseCategoryCreateView,
    ExpenseCategoryEditView,
    ExpenseCategoryListView,
    ExpenseCreateView,
    ExpenseEditView,
    ExpenseListView,
    ImportFromPretalxView,
    ImportPretalxStreamView,
    ManualPaymentView,
    OrderDetailView,
    OrderListView,
    PretalxEventSearchView,
    ReceiptApproveView,
    ReceiptFlagView,
    ReceiptReviewDetailView,
    ReceiptReviewQueueView,
    RoomCreateView,
    RoomEditView,
    RoomListView,
    RoomSearchView,
    ScheduleSlotEditView,
    ScheduleSlotListView,
    SectionCreateView,
    SectionEditView,
    SectionListView,
    SpeakerDetailView,
    SpeakerListView,
    SponsorCreateView,
    SponsorEditView,
    SponsorLevelCreateView,
    SponsorLevelEditView,
    SponsorLevelListView,
    SponsorManageListView,
    SyncPretalxStreamView,
    SyncPretalxView,
    SyncSponsorsView,
    TalkDetailView,
    TalkEditView,
    TalkListView,
    TicketTypeCreateView,
    TicketTypeEditView,
    TicketTypeListView,
    TravelGrantDisburseView,
    TravelGrantManageListView,
    TravelGrantReviewView,
    TravelGrantSendMessageView,
    VoucherCreateView,
    VoucherEditView,
    VoucherListView,
)
from django_program.manage.views_checkin import CheckInDashboardView, CheckInScannerView
from django_program.manage.views_letters import (
    LetterRequestBulkGenerateView,
    LetterRequestDownloadView,
    LetterRequestGenerateView,
    LetterRequestListView,
    LetterRequestReviewView,
    LetterRequestSendView,
)
from django_program.manage.views_terminal import TerminalPOSView

app_name = "manage"

urlpatterns = [
    path("", ConferenceListView.as_view(), name="conference-list"),
    path("import/", ImportFromPretalxView.as_view(), name="import-pretalx"),
    path("import/stream/", ImportPretalxStreamView.as_view(), name="import-pretalx-stream"),
    path("api/pretalx-events/", PretalxEventSearchView.as_view(), name="pretalx-event-search"),
    path("<slug:conference_slug>/", DashboardView.as_view(), name="dashboard"),
    path("<slug:conference_slug>/edit/", ConferenceEditView.as_view(), name="conference-edit"),
    path("<slug:conference_slug>/sync/", SyncPretalxView.as_view(), name="sync-pretalx"),
    path("<slug:conference_slug>/sync/stream/", SyncPretalxStreamView.as_view(), name="sync-pretalx-stream"),
    path("<slug:conference_slug>/sync-sponsors/", SyncSponsorsView.as_view(), name="sync-sponsors"),
    path("<slug:conference_slug>/sections/", SectionListView.as_view(), name="section-list"),
    path("<slug:conference_slug>/sections/add/", SectionCreateView.as_view(), name="section-add"),
    path(
        "<slug:conference_slug>/sections/<int:pk>/edit/",
        SectionEditView.as_view(),
        name="section-edit",
    ),
    path("<slug:conference_slug>/rooms/", RoomListView.as_view(), name="room-list"),
    path("<slug:conference_slug>/rooms/add/", RoomCreateView.as_view(), name="room-add"),
    path(
        "<slug:conference_slug>/rooms/<int:pk>/edit/",
        RoomEditView.as_view(),
        name="room-edit",
    ),
    path("<slug:conference_slug>/speakers/", SpeakerListView.as_view(), name="speaker-list"),
    path("<slug:conference_slug>/speakers/<int:pk>/", SpeakerDetailView.as_view(), name="speaker-detail"),
    path("<slug:conference_slug>/talks/", TalkListView.as_view(), name="talk-list"),
    path("<slug:conference_slug>/talks/type/<slug:type_slug>/", TalkListView.as_view(), name="talk-list-by-type"),
    path("<slug:conference_slug>/talks/<int:pk>/", TalkDetailView.as_view(), name="talk-detail"),
    path(
        "<slug:conference_slug>/talks/<int:pk>/edit/",
        TalkEditView.as_view(),
        name="talk-edit",
    ),
    path("<slug:conference_slug>/schedule/", ScheduleSlotListView.as_view(), name="schedule-list"),
    path(
        "<slug:conference_slug>/schedule/<int:pk>/edit/",
        ScheduleSlotEditView.as_view(),
        name="slot-edit",
    ),
    path("<slug:conference_slug>/sponsor-levels/", SponsorLevelListView.as_view(), name="sponsor-level-list"),
    path("<slug:conference_slug>/sponsor-levels/add/", SponsorLevelCreateView.as_view(), name="sponsor-level-add"),
    path(
        "<slug:conference_slug>/sponsor-levels/<int:pk>/edit/",
        SponsorLevelEditView.as_view(),
        name="sponsor-level-edit",
    ),
    path("<slug:conference_slug>/sponsors/", SponsorManageListView.as_view(), name="sponsor-manage-list"),
    path("<slug:conference_slug>/sponsors/add/", SponsorCreateView.as_view(), name="sponsor-add"),
    path(
        "<slug:conference_slug>/sponsors/<int:pk>/edit/",
        SponsorEditView.as_view(),
        name="sponsor-edit",
    ),
    path("<slug:conference_slug>/api/rooms/", RoomSearchView.as_view(), name="room-search"),
    path("<slug:conference_slug>/activities/", ActivityManageListView.as_view(), name="activity-list"),
    path("<slug:conference_slug>/activities/add/", ActivityCreateView.as_view(), name="activity-add"),
    path(
        "<slug:conference_slug>/activities/<int:pk>/edit/",
        ActivityEditView.as_view(),
        name="activity-edit",
    ),
    path(
        "<slug:conference_slug>/activities/<int:pk>/dashboard/",
        ActivityDashboardView.as_view(),
        name="activity-dashboard",
    ),
    path(
        "<slug:conference_slug>/activities/<int:pk>/dashboard/export/",
        ActivityDashboardExportView.as_view(),
        name="activity-dashboard-export",
    ),
    path(
        "<slug:conference_slug>/activities/<int:pk>/dashboard/<int:signup_pk>/promote/",
        ActivityPromoteSignupView.as_view(),
        name="activity-promote-signup",
    ),
    path("<slug:conference_slug>/travel-grants/", TravelGrantManageListView.as_view(), name="travel-grant-list"),
    path(
        "<slug:conference_slug>/travel-grants/<int:pk>/review/",
        TravelGrantReviewView.as_view(),
        name="travel-grant-review",
    ),
    path(
        "<slug:conference_slug>/travel-grants/<int:pk>/message/",
        TravelGrantSendMessageView.as_view(),
        name="travel-grant-send-message",
    ),
    path(
        "<slug:conference_slug>/travel-grants/<int:pk>/disburse/",
        TravelGrantDisburseView.as_view(),
        name="travel-grant-disburse",
    ),
    path("<slug:conference_slug>/receipts/review/", ReceiptReviewQueueView.as_view(), name="receipt-review-queue"),
    path("<slug:conference_slug>/receipts/<int:pk>/", ReceiptReviewDetailView.as_view(), name="receipt-review-detail"),
    path("<slug:conference_slug>/receipts/<int:pk>/approve/", ReceiptApproveView.as_view(), name="receipt-approve"),
    path("<slug:conference_slug>/receipts/<int:pk>/flag/", ReceiptFlagView.as_view(), name="receipt-flag"),
    # Registration management
    path("<slug:conference_slug>/attendees/", AttendeeListView.as_view(), name="attendee-list"),
    path("<slug:conference_slug>/attendees/<int:pk>/", AttendeeDetailView.as_view(), name="attendee-detail"),
    path("<slug:conference_slug>/ticket-types/", TicketTypeListView.as_view(), name="ticket-type-list"),
    path("<slug:conference_slug>/ticket-types/add/", TicketTypeCreateView.as_view(), name="ticket-type-add"),
    path(
        "<slug:conference_slug>/ticket-types/<int:pk>/edit/",
        TicketTypeEditView.as_view(),
        name="ticket-type-edit",
    ),
    path("<slug:conference_slug>/addons/", AddOnListView.as_view(), name="addon-list"),
    path("<slug:conference_slug>/addons/add/", AddOnCreateView.as_view(), name="addon-add"),
    path(
        "<slug:conference_slug>/addons/<int:pk>/edit/",
        AddOnEditView.as_view(),
        name="addon-edit",
    ),
    path("<slug:conference_slug>/vouchers/", VoucherListView.as_view(), name="voucher-list"),
    path("<slug:conference_slug>/vouchers/add/", VoucherCreateView.as_view(), name="voucher-add"),
    path(
        "<slug:conference_slug>/vouchers/<int:pk>/edit/",
        VoucherEditView.as_view(),
        name="voucher-edit",
    ),
    path("<slug:conference_slug>/orders/", OrderListView.as_view(), name="order-list"),
    path("<slug:conference_slug>/orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "<slug:conference_slug>/orders/<int:pk>/payment/",
        ManualPaymentView.as_view(),
        name="order-manual-payment",
    ),
    # --- Expenses ---
    path("<slug:conference_slug>/expenses/", ExpenseListView.as_view(), name="expense-list"),
    path("<slug:conference_slug>/expenses/add/", ExpenseCreateView.as_view(), name="expense-add"),
    path(
        "<slug:conference_slug>/expenses/<int:pk>/edit/",
        ExpenseEditView.as_view(),
        name="expense-edit",
    ),
    path(
        "<slug:conference_slug>/expense-categories/",
        ExpenseCategoryListView.as_view(),
        name="expense-category-list",
    ),
    path(
        "<slug:conference_slug>/expense-categories/add/",
        ExpenseCategoryCreateView.as_view(),
        name="expense-category-add",
    ),
    path(
        "<slug:conference_slug>/expense-categories/<int:pk>/edit/",
        ExpenseCategoryEditView.as_view(),
        name="expense-category-edit",
    ),
    # --- Conditions & Discounts ---
    path("<slug:conference_slug>/conditions/", ConditionListView.as_view(), name="condition-list"),
    path(
        "<slug:conference_slug>/conditions/<slug:type_slug>/add/",
        ConditionCreateView.as_view(),
        name="condition-add",
    ),
    path(
        "<slug:conference_slug>/conditions/<slug:type_slug>/<int:pk>/edit/",
        ConditionEditView.as_view(),
        name="condition-edit",
    ),
    # --- Badges ---
    path("<slug:conference_slug>/badges/", BadgeListView.as_view(), name="badge-list"),
    path("<slug:conference_slug>/badges/templates/", BadgeTemplateListView.as_view(), name="badge-template-list"),
    path("<slug:conference_slug>/badges/templates/add/", BadgeTemplateCreateView.as_view(), name="badge-template-add"),
    path(
        "<slug:conference_slug>/badges/templates/<int:pk>/edit/",
        BadgeTemplateEditView.as_view(),
        name="badge-template-edit",
    ),
    path(
        "<slug:conference_slug>/badges/templates/<int:pk>/preview/",
        BadgePreviewView.as_view(),
        name="badge-template-preview",
    ),
    path("<slug:conference_slug>/badges/generate/", BadgeBulkGenerateView.as_view(), name="badge-bulk-generate"),
    path("<slug:conference_slug>/badges/download/", BadgeBulkDownloadView.as_view(), name="badge-bulk-download"),
    path(
        "<slug:conference_slug>/badges/<int:pk>/download/",
        BadgeDownloadView.as_view(),
        name="badge-download",
    ),
    # --- Check-in ---
    path("<slug:conference_slug>/checkin/", CheckInDashboardView.as_view(), name="checkin-dashboard"),
    path("<slug:conference_slug>/checkin/scanner/", CheckInScannerView.as_view(), name="checkin-scanner"),
    # --- Terminal POS ---
    path("<slug:conference_slug>/terminal/", TerminalPOSView.as_view(), name="terminal-pos"),
    # --- Visa/Invitation Letters ---
    path("<slug:conference_slug>/letters/", LetterRequestListView.as_view(), name="letter-list"),
    path("<slug:conference_slug>/letters/<int:pk>/", LetterRequestReviewView.as_view(), name="letter-review"),
    path(
        "<slug:conference_slug>/letters/<int:pk>/generate/",
        LetterRequestGenerateView.as_view(),
        name="letter-generate",
    ),
    path(
        "<slug:conference_slug>/letters/<int:pk>/send/",
        LetterRequestSendView.as_view(),
        name="letter-send",
    ),
    path(
        "<slug:conference_slug>/letters/<int:pk>/download/",
        LetterRequestDownloadView.as_view(),
        name="letter-download",
    ),
    path(
        "<slug:conference_slug>/letters/bulk-generate/",
        LetterRequestBulkGenerateView.as_view(),
        name="letter-bulk-generate",
    ),
    # --- Bulk Purchases ---
    path("<slug:conference_slug>/bulk-purchases/", include("django_program.manage.urls_bulk_purchases")),
    # --- Voucher Bulk Generation ---
    path("<slug:conference_slug>/vouchers/bulk/", include("django_program.manage.urls_vouchers")),
    # --- Financial Dashboard ---
    path("<slug:conference_slug>/financial/", include("django_program.manage.urls_financial")),
    # --- Reports ---
    path("<slug:conference_slug>/reports/", include("django_program.manage.urls_reports")),
    # --- Analytics & KPI Dashboard ---
    path("<slug:conference_slug>/analytics/", include("django_program.manage.urls_analytics")),
    # --- Pretalx Overrides ---
    path("<slug:conference_slug>/overrides/", include("django_program.manage.urls_overrides")),
]
