"""URL configuration for the conference management dashboard.

Mount under a prefix in the host project::

    urlpatterns = [
        path("manage/", include("django_program.manage.urls")),
    ]
"""

from django.urls import path

from django_program.manage.views import (
    ActivityCreateView,
    ActivityDashboardExportView,
    ActivityDashboardView,
    ActivityEditView,
    ActivityManageListView,
    ActivityPromoteSignupView,
    AddOnCreateView,
    AddOnEditView,
    AddOnListView,
    ConferenceEditView,
    ConferenceListView,
    DashboardView,
    ImportFromPretalxView,
    ImportPretalxStreamView,
    ManualPaymentView,
    OrderDetailView,
    OrderListView,
    PretalxEventSearchView,
    ReceiptApproveView,
    ReceiptFlagView,
    ReceiptReviewDetailView,
    ReceiptReviewQueueView,
    RoomCreateView,
    RoomEditView,
    RoomListView,
    RoomSearchView,
    ScheduleSlotEditView,
    ScheduleSlotListView,
    SectionCreateView,
    SectionEditView,
    SectionListView,
    SpeakerDetailView,
    SpeakerListView,
    SponsorCreateView,
    SponsorEditView,
    SponsorLevelCreateView,
    SponsorLevelEditView,
    SponsorLevelListView,
    SponsorManageListView,
    SyncPretalxStreamView,
    SyncPretalxView,
    SyncSponsorsView,
    TalkDetailView,
    TalkEditView,
    TalkListView,
    TicketTypeCreateView,
    TicketTypeEditView,
    TicketTypeListView,
    TravelGrantDisburseView,
    TravelGrantManageListView,
    TravelGrantReviewView,
    TravelGrantSendMessageView,
    VoucherCreateView,
    VoucherEditView,
    VoucherListView,
)

app_name = "manage"

urlpatterns = [
    path("", ConferenceListView.as_view(), name="conference-list"),
    path("import/", ImportFromPretalxView.as_view(), name="import-pretalx"),
    path("import/stream/", ImportPretalxStreamView.as_view(), name="import-pretalx-stream"),
    path("api/pretalx-events/", PretalxEventSearchView.as_view(), name="pretalx-event-search"),
    path("<slug:conference_slug>/", DashboardView.as_view(), name="dashboard"),
    path("<slug:conference_slug>/edit/", ConferenceEditView.as_view(), name="conference-edit"),
    path("<slug:conference_slug>/sync/", SyncPretalxView.as_view(), name="sync-pretalx"),
    path("<slug:conference_slug>/sync/stream/", SyncPretalxStreamView.as_view(), name="sync-pretalx-stream"),
    path("<slug:conference_slug>/sync-sponsors/", SyncSponsorsView.as_view(), name="sync-sponsors"),
    path("<slug:conference_slug>/sections/", SectionListView.as_view(), name="section-list"),
    path("<slug:conference_slug>/sections/add/", SectionCreateView.as_view(), name="section-add"),
    path(
        "<slug:conference_slug>/sections/<int:pk>/edit/",
        SectionEditView.as_view(),
        name="section-edit",
    ),
    path("<slug:conference_slug>/rooms/", RoomListView.as_view(), name="room-list"),
    path("<slug:conference_slug>/rooms/add/", RoomCreateView.as_view(), name="room-add"),
    path(
        "<slug:conference_slug>/rooms/<int:pk>/edit/",
        RoomEditView.as_view(),
        name="room-edit",
    ),
    path("<slug:conference_slug>/speakers/", SpeakerListView.as_view(), name="speaker-list"),
    path("<slug:conference_slug>/speakers/<int:pk>/", SpeakerDetailView.as_view(), name="speaker-detail"),
    path("<slug:conference_slug>/talks/", TalkListView.as_view(), name="talk-list"),
    path("<slug:conference_slug>/talks/type/<slug:type_slug>/", TalkListView.as_view(), name="talk-list-by-type"),
    path("<slug:conference_slug>/talks/<int:pk>/", TalkDetailView.as_view(), name="talk-detail"),
    path(
        "<slug:conference_slug>/talks/<int:pk>/edit/",
        TalkEditView.as_view(),
        name="talk-edit",
    ),
    path("<slug:conference_slug>/schedule/", ScheduleSlotListView.as_view(), name="schedule-list"),
    path(
        "<slug:conference_slug>/schedule/<int:pk>/edit/",
        ScheduleSlotEditView.as_view(),
        name="slot-edit",
    ),
    path("<slug:conference_slug>/sponsor-levels/", SponsorLevelListView.as_view(), name="sponsor-level-list"),
    path("<slug:conference_slug>/sponsor-levels/add/", SponsorLevelCreateView.as_view(), name="sponsor-level-add"),
    path(
        "<slug:conference_slug>/sponsor-levels/<int:pk>/edit/",
        SponsorLevelEditView.as_view(),
        name="sponsor-level-edit",
    ),
    path("<slug:conference_slug>/sponsors/", SponsorManageListView.as_view(), name="sponsor-manage-list"),
    path("<slug:conference_slug>/sponsors/add/", SponsorCreateView.as_view(), name="sponsor-add"),
    path(
        "<slug:conference_slug>/sponsors/<int:pk>/edit/",
        SponsorEditView.as_view(),
        name="sponsor-edit",
    ),
    path("<slug:conference_slug>/api/rooms/", RoomSearchView.as_view(), name="room-search"),
    path("<slug:conference_slug>/activities/", ActivityManageListView.as_view(), name="activity-list"),
    path("<slug:conference_slug>/activities/add/", ActivityCreateView.as_view(), name="activity-add"),
    path(
        "<slug:conference_slug>/activities/<int:pk>/edit/",
        ActivityEditView.as_view(),
        name="activity-edit",
    ),
    path(
        "<slug:conference_slug>/activities/<int:pk>/dashboard/",
        ActivityDashboardView.as_view(),
        name="activity-dashboard",
    ),
    path(
        "<slug:conference_slug>/activities/<int:pk>/dashboard/export/",
        ActivityDashboardExportView.as_view(),
        name="activity-dashboard-export",
    ),
    path(
        "<slug:conference_slug>/activities/<int:pk>/dashboard/<int:signup_pk>/promote/",
        ActivityPromoteSignupView.as_view(),
        name="activity-promote-signup",
    ),
    path("<slug:conference_slug>/travel-grants/", TravelGrantManageListView.as_view(), name="travel-grant-list"),
    path(
        "<slug:conference_slug>/travel-grants/<int:pk>/review/",
        TravelGrantReviewView.as_view(),
        name="travel-grant-review",
    ),
    path(
        "<slug:conference_slug>/travel-grants/<int:pk>/message/",
        TravelGrantSendMessageView.as_view(),
        name="travel-grant-send-message",
    ),
    path(
        "<slug:conference_slug>/travel-grants/<int:pk>/disburse/",
        TravelGrantDisburseView.as_view(),
        name="travel-grant-disburse",
    ),
    path("<slug:conference_slug>/receipts/review/", ReceiptReviewQueueView.as_view(), name="receipt-review-queue"),
    path("<slug:conference_slug>/receipts/<int:pk>/", ReceiptReviewDetailView.as_view(), name="receipt-review-detail"),
    path("<slug:conference_slug>/receipts/<int:pk>/approve/", ReceiptApproveView.as_view(), name="receipt-approve"),
    path("<slug:conference_slug>/receipts/<int:pk>/flag/", ReceiptFlagView.as_view(), name="receipt-flag"),
    # Registration management
    path("<slug:conference_slug>/ticket-types/", TicketTypeListView.as_view(), name="ticket-type-list"),
    path("<slug:conference_slug>/ticket-types/add/", TicketTypeCreateView.as_view(), name="ticket-type-add"),
    path(
        "<slug:conference_slug>/ticket-types/<int:pk>/edit/",
        TicketTypeEditView.as_view(),
        name="ticket-type-edit",
    ),
    path("<slug:conference_slug>/addons/", AddOnListView.as_view(), name="addon-list"),
    path("<slug:conference_slug>/addons/add/", AddOnCreateView.as_view(), name="addon-add"),
    path(
        "<slug:conference_slug>/addons/<int:pk>/edit/",
        AddOnEditView.as_view(),
        name="addon-edit",
    ),
    path("<slug:conference_slug>/vouchers/", VoucherListView.as_view(), name="voucher-list"),
    path("<slug:conference_slug>/vouchers/add/", VoucherCreateView.as_view(), name="voucher-add"),
    path(
        "<slug:conference_slug>/vouchers/<int:pk>/edit/",
        VoucherEditView.as_view(),
        name="voucher-edit",
    ),
    path("<slug:conference_slug>/orders/", OrderListView.as_view(), name="order-list"),
    path("<slug:conference_slug>/orders/<int:pk>/", OrderDetailView.as_view(), name="order-detail"),
    path(
        "<slug:conference_slug>/orders/<int:pk>/payment/",
        ManualPaymentView.as_view(),
        name="order-manual-payment",
    ),
]
