name: Bug Report
description: Report a bug in django-program
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the bug.
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: django-program version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: django-version
    attributes:
      label: Django version
      placeholder: "5.2"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.14"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant information (logs, screenshots, etc.).
    validations:
      required: false
