name: Documentation
description: Suggest a documentation improvement
labels: [documentation]
body:
  - type: input
    id: page
    attributes:
      label: Page or section
      description: Which page or section needs improvement?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's wrong or missing?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested change
      description: How would you improve it?
    validations:
      required: false
