# Generated by Django 5.2.11 on 2026-02-11 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("program_conference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                (
                    "total_quantity",
                    models.PositiveIntegerField(default=0, help_text="Maximum number available. 0 means unlimited."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "voucher_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the voucher code applied at checkout.",
                        max_length=100,
                    ),
                ),
                (
                    "voucher_details",
                    models.TextField(
                        blank=True, default="", help_text="JSON snapshot of the voucher state at checkout time."
                    ),
                ),
                ("billing_name", models.CharField(blank=True, default="", max_length=200)),
                ("billing_email", models.EmailField(blank=True, default="", max_length=254)),
                ("billing_company", models.CharField(blank=True, default="", max_length=200)),
                (
                    "reference",
                    models.CharField(
                        help_text='Unique order reference, e.g. "ORD-A1B2C3".', max_length=100, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("applied", "Applied"), ("expired", "Expired")],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credits",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credits", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "applied_to_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_credits",
                        to="program_registration.order",
                    ),
                ),
                (
                    "source_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_credits",
                        to="program_registration.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("comp", "Complimentary"),
                            ("credit", "Credit"),
                            ("manual", "Manual"),
                        ],
                        default="stripe",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=200)),
                ("stripe_charge_id", models.CharField(blank=True, default="", max_length=200)),
                ("reference", models.CharField(blank=True, default="", max_length=200)),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="program_registration.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                (
                    "total_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum number of tickets available. 0 means unlimited."
                    ),
                ),
                ("limit_per_user", models.PositiveIntegerField(default=10)),
                (
                    "requires_voucher",
                    models.BooleanField(
                        default=False, help_text="When True, this ticket type is hidden unless unlocked by a voucher."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("conference", "slug")},
            },
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=300)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_line_items",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="program_registration.order",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_line_items",
                        to="program_registration.tickettype",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="addon",
            name="requires_ticket_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ticket types this add-on is available for. Empty means all.",
                related_name="available_addons",
                to="program_registration.tickettype",
            ),
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100)),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("comp", "Complimentary (100% off)"),
                            ("percentage", "Percentage discount"),
                            ("fixed_amount", "Fixed amount discount"),
                        ],
                        default="comp",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage (0-100) or fixed amount depending on voucher_type.",
                        max_digits=10,
                    ),
                ),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "unlocks_hidden_tickets",
                    models.BooleanField(
                        default=False, help_text="When True, reveals ticket types that require a voucher."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Add-ons this voucher applies to. Empty means all.",
                        related_name="vouchers",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "applicable_ticket_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ticket types this voucher applies to. Empty means all.",
                        related_name="vouchers",
                        to="program_registration.tickettype",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "unique_together": {("conference", "code")},
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("checked_out", "Checked Out"),
                            ("expired", "Expired"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="carts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to="program_registration.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="program_registration.cart",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items",
                        to="program_registration.tickettype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("addon__isnull", True), ("ticket_type__isnull", False)),
                            models.Q(("addon__isnull", False), ("ticket_type__isnull", True)),
                            _connector="OR",
                        ),
                        name="registration_cartitem_exactly_one_type",
                    )
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="addon",
            unique_together={("conference", "slug")},
        ),
    ]
