# Generated by Django 5.2.11 on 2026-02-11 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0002_encrypt_stripe_fields"),
        ("program_registration", "0002_fix_cartitem_on_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_id", models.CharField(max_length=200, unique=True)),
                ("kind", models.CharField(max_length=200)),
                ("livemode", models.BooleanField(default=False)),
                ("payload", models.JSONField(default=dict)),
                ("customer_id", models.CharField(blank=True, default="", max_length=200)),
                ("processed", models.BooleanField(default=False)),
                ("api_version", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="succeeded",
                help_text="Defaults to SUCCEEDED for backward compatibility with existing data.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EventProcessingException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.TextField(blank=True, default="")),
                ("message", models.CharField(max_length=500)),
                ("traceback", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_exceptions",
                        to="program_registration.stripeevent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_customer_id", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customers",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stripe_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("conference", "stripe_customer_id"), ("user", "conference")},
            },
        ),
    ]
