# Generated by Django 5.2.11 on 2026-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0003_stripeevent_payment_status_eventprocessingexception_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ticket_type__isnull", False)),
                fields=("cart", "ticket_type"),
                name="registration_cartitem_unique_ticket_per_cart",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("addon__isnull", False)),
                fields=("cart", "addon"),
                name="registration_cartitem_unique_addon_per_cart",
            ),
        ),
    ]
