# Generated by Django 5.2.11 on 2026-02-11

from django.db import migrations, models


def initialize_credit_remaining_amount(apps, _schema_editor):
    Credit = apps.get_model("program_registration", "Credit")

    Credit.objects.filter(status="available").update(remaining_amount=models.F("amount"))
    Credit.objects.exclude(status="available").update(remaining_amount=0)


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0004_cartitem_registration_cartitem_unique_ticket_per_cart_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="remaining_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Unspent credit balance that can be applied to future orders.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="hold_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When set on pending orders, inventory is reserved until this timestamp.",
                null=True,
            ),
        ),
        migrations.RunPython(initialize_credit_remaining_amount, migrations.RunPython.noop),
    ]
