# Generated by Django 5.2.11 on 2026-03-17 00:14

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("program_conference", "0005_merge_0004_add_feature_flags_0004_add_total_capacity"),
        ("program_registration", "0005_order_hold_expires_at_credit_remaining_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountForCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0, help_text="Lower values are evaluated first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="Percentage discount to apply (0-100).", max_digits=5
                    ),
                ),
                (
                    "apply_to_tickets",
                    models.BooleanField(default=True, help_text="Apply this discount to all ticket types."),
                ),
                ("apply_to_addons", models.BooleanField(default=True, help_text="Apply this discount to all add-ons.")),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum number of times this discount can be used. 0 means unlimited."
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_conditions",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "category discount",
                "verbose_name_plural": "category discounts",
                "ordering": ["priority", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DiscountForProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0, help_text="Lower values are evaluated first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum items this discount applies to. 0 means unlimited."
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum number of times this discount can be used. 0 means unlimited."
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "applicable_addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Add-ons this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "applicable_ticket_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ticket types this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.tickettype",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_conditions",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "product discount",
                "verbose_name_plural": "product discounts",
                "ordering": ["priority", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupMemberCondition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0, help_text="Lower values are evaluated first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum items this discount applies to. 0 means unlimited."
                    ),
                ),
                (
                    "applicable_addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Add-ons this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "applicable_ticket_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ticket types this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.tickettype",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_conditions",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        help_text="User must be a member of at least one of these groups.",
                        related_name="condition_discounts",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "group member condition",
                "verbose_name_plural": "group member conditions",
                "ordering": ["priority", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncludedProductCondition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0, help_text="Lower values are evaluated first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum items this discount applies to. 0 means unlimited."
                    ),
                ),
                (
                    "applicable_addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Add-ons this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "applicable_ticket_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ticket types this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.tickettype",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_conditions",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "enabling_ticket_types",
                    models.ManyToManyField(
                        help_text="User must have a paid order containing one of these ticket types.",
                        related_name="enabling_conditions",
                        to="program_registration.tickettype",
                    ),
                ),
            ],
            options={
                "verbose_name": "included product condition",
                "verbose_name_plural": "included product conditions",
                "ordering": ["priority", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpeakerCondition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0, help_text="Lower values are evaluated first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum items this discount applies to. 0 means unlimited."
                    ),
                ),
                (
                    "is_presenter",
                    models.BooleanField(
                        default=True, help_text="Apply to primary speakers (those listed as speaker on a talk)."
                    ),
                ),
                (
                    "is_copresenter",
                    models.BooleanField(default=False, help_text="Apply to additional speakers / copresenters."),
                ),
                (
                    "applicable_addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Add-ons this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "applicable_ticket_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ticket types this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.tickettype",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_conditions",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "speaker condition",
                "verbose_name_plural": "speaker conditions",
                "ordering": ["priority", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TimeOrStockLimitCondition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0, help_text="Lower values are evaluated first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum items this discount applies to. 0 means unlimited."
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum number of times this condition can be used. 0 means unlimited."
                    ),
                ),
                ("times_used", models.PositiveIntegerField(default=0)),
                (
                    "applicable_addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Add-ons this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "applicable_ticket_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Ticket types this discount applies to. Empty means all.",
                        related_name="%(class)s_discounts",
                        to="program_registration.tickettype",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_conditions",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "verbose_name": "time/stock limit condition",
                "verbose_name_plural": "time/stock limit conditions",
                "ordering": ["priority", "name"],
                "abstract": False,
            },
        ),
    ]
