# Generated by Django 5.2.11 on 2026-03-17 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0006_attendee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendees",
                to="program_registration.order",
            ),
        ),
    ]
