# Generated by Django 5.2.11 on 2026-03-17 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0006_discountforcategory_discountforproduct_and_more"),
        ("program_registration", "0007_alter_attendee_order"),
    ]

    operations = []
