# Generated by Django 5.2.11 on 2026-03-17 02:35

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

import django_program.registration.conditions


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0005_merge_0004_add_feature_flags_0004_add_total_capacity"),
        ("program_registration", "0008_merge_20260316_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountforproduct",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                max_digits=10,
                validators=[django_program.registration.conditions._validate_discount_value],
            ),
        ),
        migrations.AlterField(
            model_name="groupmembercondition",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                max_digits=10,
                validators=[django_program.registration.conditions._validate_discount_value],
            ),
        ),
        migrations.AlterField(
            model_name="includedproductcondition",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                max_digits=10,
                validators=[django_program.registration.conditions._validate_discount_value],
            ),
        ),
        migrations.AlterField(
            model_name="speakercondition",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                max_digits=10,
                validators=[django_program.registration.conditions._validate_discount_value],
            ),
        ),
        migrations.AlterField(
            model_name="timeorstocklimitcondition",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage (0-100) or fixed amount depending on discount_type.",
                max_digits=10,
                validators=[django_program.registration.conditions._validate_discount_value],
            ),
        ),
        migrations.CreateModel(
            name="BadgeTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                ("width_mm", models.PositiveIntegerField(default=86, help_text="Badge width in millimeters.")),
                ("height_mm", models.PositiveIntegerField(default=54, help_text="Badge height in millimeters.")),
                ("show_name", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=False)),
                ("show_company", models.BooleanField(default=False)),
                ("show_ticket_type", models.BooleanField(default=True)),
                ("show_qr_code", models.BooleanField(default=True)),
                ("show_conference_name", models.BooleanField(default=True)),
                ("background_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("text_color", models.CharField(default="#000000", max_length=7)),
                ("accent_color", models.CharField(default="#4338CA", max_length=7)),
                ("logo", models.ImageField(blank=True, default="", upload_to="badges/logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge_templates",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("format", models.CharField(choices=[("pdf", "PDF"), ("png", "PNG")], default="pdf", max_length=10)),
                ("file", models.FileField(blank=True, default="", upload_to="badges/generated/")),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="program_registration.attendee",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="badges",
                        to="program_registration.badgetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="badgetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("conference",),
                name="registration_badgetemplate_one_default_per_conference",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="badgetemplate",
            unique_together={("conference", "slug")},
        ),
    ]
