# Generated by Django 5.2.11 on 2026-03-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0009_alter_discountforproduct_discount_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgetemplate",
            name="height_mm",
            field=models.PositiveIntegerField(
                default=152, help_text="Badge height in millimeters (default 152mm / 6 inches, portrait)."
            ),
        ),
        migrations.AlterField(
            model_name="badgetemplate",
            name="width_mm",
            field=models.PositiveIntegerField(
                default=102, help_text="Badge width in millimeters (default 102mm / 4 inches)."
            ),
        ),
    ]
