# Generated by Django 5.2.11 on 2026-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0010_badge_portrait_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgetemplate",
            name="background_image",
            field=models.ImageField(
                blank=True,
                default="",
                help_text="Custom background image from a designer. Overlaid text is rendered on top.",
                upload_to="badges/backgrounds/",
            ),
        ),
    ]
