# Generated by Django 5.2.11 on 2026-03-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0011_badge_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgetemplate",
            name="font_body",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Font name or path for body text (company, email). Leave blank for Helvetica.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="badgetemplate",
            name="font_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Font name or path for the name field. Searched in STATICFILES_DIRS, STATIC_ROOT, then system fonts. Leave blank for Helvetica.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="badgetemplate",
            name="ticket_banner_position",
            field=models.CharField(
                choices=[
                    ("below_header", "Below header"),
                    ("above_name", "Above name"),
                    ("below_name", "Below name"),
                    ("bottom", "Bottom of badge"),
                ],
                default="below_header",
                help_text="Where to place the ticket type banner (Speaker, Sponsor, etc.).",
                max_length=20,
            ),
        ),
    ]
