# Generated by Django 5.2.11 on 2026-03-17 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0012_badge_fonts_banner_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgetemplate",
            name="accent_color",
            field=models.CharField(
                default="#4338CA",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Enter a valid hex color (e.g. #FF0000)."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="badgetemplate",
            name="background_color",
            field=models.CharField(
                default="#FFFFFF",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Enter a valid hex color (e.g. #FF0000)."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="badgetemplate",
            name="text_color",
            field=models.CharField(
                default="#000000",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$", "Enter a valid hex color (e.g. #FF0000)."
                    )
                ],
            ),
        ),
    ]
