# Generated by Django 5.2.11 on 2026-03-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0013_alter_badgetemplate_accent_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="utm_campaign",
            field=models.CharField(
                blank=True, default="", help_text="UTM campaign parameter from registration URL.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="utm_medium",
            field=models.CharField(
                blank=True, default="", help_text="UTM medium parameter from registration URL.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="utm_source",
            field=models.CharField(
                blank=True, default="", help_text="UTM source parameter from registration URL.", max_length=200
            ),
        ),
    ]
