# Generated by Django 5.2.11 on 2026-03-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0014_order_utm_campaign_order_utm_medium_order_utm_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="addon",
            name="bulk_enabled",
            field=models.BooleanField(
                default=False, help_text="Allow this add-on to be offered in bulk purchase deals."
            ),
        ),
        migrations.AddField(
            model_name="tickettype",
            name="bulk_enabled",
            field=models.BooleanField(
                default=False, help_text="Allow this ticket type to be offered in bulk purchase deals."
            ),
        ),
    ]
