# Generated by Django 5.2.11 on 2026-03-19 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0008_kpitargets"),
        ("program_registration", "0015_addon_bulk_enabled_tickettype_bulk_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Station identifier, e.g. "Door A", "Registration Desk 1".',
                        max_length=100,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="program_registration.attendee",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who performed this check-in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_in_at"],
            },
        ),
        migrations.CreateModel(
            name="DoorCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Station identifier, e.g. "Tutorial Room 1", "Meal Hall".',
                        max_length=100,
                    ),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="door_checks",
                        to="program_registration.addon",
                    ),
                ),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="door_checks",
                        to="program_registration.attendee",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who performed this door check.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_door_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="door_checks",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="door_checks",
                        to="program_registration.tickettype",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductRedemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="program_registration.attendee",
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "order_line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="program_registration.orderlineitem",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who performed this redemption.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
                "unique_together": {("attendee", "order_line_item")},
            },
        ),
    ]
