# Generated by Django 5.2.11 on 2026-03-19 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0016_checkin_doorcheck_productredemption"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productredemption",
            unique_together=set(),
        ),
    ]
