# Generated by Django 5.2.11 on 2026-03-19 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0008_kpitargets"),
        ("program_registration", "0017_alter_productredemption_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("terminal", "Terminal"),
                    ("comp", "Complimentary"),
                    ("credit", "Credit"),
                    ("manual", "Manual"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TerminalPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "terminal_id",
                    models.CharField(blank=True, default="", help_text="Stripe Terminal Location ID.", max_length=200),
                ),
                (
                    "reader_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe Terminal Reader ID that processed the payment.",
                        max_length=200,
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        help_text="Stripe PaymentIntent ID for this terminal transaction.", max_length=200
                    ),
                ),
                (
                    "capture_status",
                    models.CharField(
                        choices=[
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="authorized",
                        max_length=20,
                    ),
                ),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("card_brand", models.CharField(blank=True, default="", max_length=50)),
                ("card_last4", models.CharField(blank=True, default="", max_length=4)),
                ("receipt_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_payments",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_detail",
                        to="program_registration.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
