# Generated by Django 5.2.11 on 2026-03-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0020_purchaseorder_purchaseordercreditnote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="qbo_invoice_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="QuickBooks Online Invoice ID, set after invoice creation.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="qbo_invoice_url",
            field=models.URLField(
                blank=True, default="", help_text="Public URL to the QBO invoice for the customer.", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="stripe_invoice_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe Invoice ID (e.g. in_xxx) when sent via Stripe Invoicing.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="stripe_invoice_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Stripe-hosted invoice URL for the customer to pay online.",
                max_length=500,
            ),
        ),
    ]
