# Generated by Django 5.2.11 on 2026-02-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("program_conference", "0002_encrypt_stripe_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("website_url", models.URLField(blank=True, default="")),
                (
                    "logo",
                    models.ImageField(blank=True, default="", upload_to="sponsors/logos/"),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_complete", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="program_sponsors.sponsor",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "benefits_summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Plain text summary of benefits for this level.",
                    ),
                ),
                (
                    "comp_ticket_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of complimentary tickets to auto-generate for sponsors at this level.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_levels",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "unique_together": {("conference", "slug")},
            },
        ),
        migrations.AddField(
            model_name="sponsor",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sponsors",
                to="program_sponsors.sponsorlevel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sponsor",
            unique_together={("conference", "slug")},
        ),
    ]
