# Generated by Django 5.2.11 on 2026-02-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_sponsors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="sponsorlevel",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
