# Generated by Django 5.2.11 on 2026-02-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_sponsors", "0002_alter_sponsor_slug_alter_sponsorlevel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External identifier from the PSF sponsorship API.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sponsor",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Remote logo URL from the PSF sponsorship API.",
            ),
        ),
    ]
