# Generated by Django 5.2.11 on 2026-02-14 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0003_conference_address"),
        ("program_sponsors", "0003_add_external_id_and_logo_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "override_name",
                    models.CharField(blank=True, default="", help_text="Override the sponsor name.", max_length=200),
                ),
                (
                    "override_description",
                    models.TextField(blank=True, default="", help_text="Override the sponsor description."),
                ),
                (
                    "override_website_url",
                    models.URLField(blank=True, default="", help_text="Override the sponsor website URL."),
                ),
                (
                    "override_logo_url",
                    models.URLField(blank=True, default="", help_text="Override the sponsor logo URL."),
                ),
                (
                    "override_contact_name",
                    models.CharField(
                        blank=True, default="", help_text="Override the sponsor contact name.", max_length=200
                    ),
                ),
                (
                    "override_contact_email",
                    models.EmailField(
                        blank=True, default="", help_text="Override the sponsor contact email.", max_length=254
                    ),
                ),
                (
                    "override_is_active",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Override the sponsor active status. Leave blank for no override.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Internal note explaining the reason for this override."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_overrides",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sponsor_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "override_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override the sponsor level.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsor_overrides",
                        to="program_sponsors.sponsorlevel",
                    ),
                ),
                (
                    "sponsor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override",
                        to="program_sponsors.sponsor",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
