# Generated by Django 5.2.11 on 2026-03-18 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_conference", "0008_kpitargets"),
        ("program_registration", "0014_order_utm_campaign_order_utm_medium_order_utm_source"),
        ("program_sponsors", "0004_sponsoroverride"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkPurchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(help_text="Number of voucher codes to generate.")),
                (
                    "product_description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Description of the ticket type or product this purchase covers.",
                        max_length=300,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("stripe_payment_intent_id", models.CharField(blank=True, default="", max_length=200)),
                ("stripe_checkout_session_id", models.CharField(blank=True, default="", max_length=200)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "voucher_config",
                    models.JSONField(
                        default=dict,
                        help_text="Voucher generation parameters: voucher_type, discount_value, max_uses, valid_from, valid_until.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bulk_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_purchases",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_bulk_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_purchases",
                        to="program_sponsors.sponsor",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to the ticket type these vouchers are for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_purchases",
                        to="program_registration.tickettype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkPurchaseVoucher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="program_sponsors.bulkpurchase",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_purchase_links",
                        to="program_registration.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("bulk_purchase", "voucher")},
            },
        ),
    ]
