# Generated by Django 5.2.11 on 2026-03-18 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_registration", "0015_addon_bulk_enabled_tickettype_bulk_enabled"),
        ("program_sponsors", "0005_bulkpurchase_bulkpurchasevoucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkpurchase",
            name="addon",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to the add-on these vouchers are for (shirts, tutorials, etc.).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulk_purchases",
                to="program_registration.addon",
            ),
        ),
    ]
