# Generated by Django 5.2.11 on 2026-03-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_sponsors", "0006_bulkpurchase_addon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkpurchase",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bulkpurchase",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="The sponsor this deal is for (leave blank for non-sponsor deals).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulk_purchases",
                to="program_sponsors.sponsor",
            ),
        ),
    ]
