# Generated by Django 5.2.11 on 2026-02-12 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("program_conference", "0002_encrypt_stripe_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("sprint", "Sprint"),
                            ("workshop", "Workshop"),
                            ("tutorial", "Tutorial"),
                            ("social", "Social Event"),
                            ("open_space", "Open Space"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, help_text="Leave blank for unlimited.", null=True),
                ),
                (
                    "requires_ticket",
                    models.BooleanField(default=False, help_text="Whether a conference ticket is required to sign up."),
                ),
                ("external_url", models.URLField(blank=True, default="", help_text="External link for more details.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="program_conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time", "name"],
                "unique_together": {("conference", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ActivitySignup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.TextField(blank=True, default="", help_text="Optional note from the attendee.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="program_programs.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_signups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("activity", "user")},
            },
        ),
        migrations.CreateModel(
            name="TravelGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("approved_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "travel_from",
                    models.CharField(help_text="City or region the applicant is traveling from.", max_length=200),
                ),
                ("reason", models.TextField(help_text="Why the applicant needs a travel grant.")),
                ("reviewer_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_grants",
                        to="program_conference.conference",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("conference", "user")},
            },
        ),
    ]
