# Generated by Django 5.2.11 on 2026-02-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("sprint", "Sprint"),
                    ("workshop", "Workshop"),
                    ("tutorial", "Tutorial"),
                    ("lightning_talk", "Lightning Talk"),
                    ("social", "Social Event"),
                    ("open_space", "Open Space"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
