# Generated by Django 5.2.11 on 2026-02-12 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_pretalx", "0004_talk_tags"),
        ("program_programs", "0002_alter_activity_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="pretalx_submission_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Pretalx submission type name to link talks (e.g. 'Tutorial', 'Workshop').",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="room",
            field=models.ForeignKey(
                blank=True,
                help_text="Pretalx room assignment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="program_pretalx.room",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this activity was last synced from Pretalx.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="talks",
            field=models.ManyToManyField(
                blank=True,
                help_text="Talks linked via submission type match during Pretalx sync.",
                related_name="activities",
                to="program_pretalx.talk",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("sprint", "Sprint"),
                    ("workshop", "Workshop"),
                    ("tutorial", "Tutorial"),
                    ("lightning_talk", "Lightning Talk"),
                    ("social", "Social Event"),
                    ("open_space", "Open Space"),
                    ("summit", "Summit"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Manual location for off-venue or non-Pretalx activities.",
                max_length=200,
            ),
        ),
    ]
