# Generated by Django 5.2.11 on 2026-02-12 03:40

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "program_programs",
            "0003_activity_pretalx_submission_type_activity_room_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="travelgrant",
            options={
                "ordering": ["-created_at"],
                "permissions": [("review_travel_grant", "Can review travel grant applications")],
            },
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("general", "General Applicant"),
                    ("staff", "Conference Staff/Volunteer"),
                    ("speaker", "Speaker"),
                    ("community", "Outstanding Community Member"),
                    ("education", "Education"),
                    ("other", "Other"),
                ],
                default="general",
                help_text="Application classification.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="days_attending",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Which conference days the applicant plans to attend.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("expert", "Expert"),
                ],
                default="",
                help_text="Python experience level.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="first_time",
            field=models.BooleanField(
                blank=True,
                help_text="Is this the applicant's first time attending?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="international",
            field=models.BooleanField(
                default=False,
                help_text="Whether the applicant is traveling internationally.",
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="involvement",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Involvement in open source projects or community.",
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="occupation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Current occupation or situation.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="promo_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Voucher/promo code for ticket.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("ticket_only", "In-Person Ticket Only"),
                    ("ticket_and_grant", "In-Person Ticket and Travel Grant"),
                ],
                default="ticket_and_grant",
                help_text="What kind of request you are submitting.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="sharing_expenses",
            field=models.BooleanField(
                default=False,
                help_text="Whether sharing travel expenses with another applicant.",
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_airfare_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Estimated airfare cost in USD.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_airfare_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Description of airfare plans.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_lodging_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Estimated lodging cost in USD.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_lodging_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Description of lodging plans.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_transit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Estimated local transit cost in USD.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_transit_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Description of local transit plans.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_visa_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Estimated visa cost in USD.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="travel_plans_visa_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Description of visa costs.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="traveling_with",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Names of other grant applicants sharing expenses.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="travelgrant",
            name="requested_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount of assistance requested in USD.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="travelgrant",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("info_needed", "Information Needed"),
                    ("offered", "Offered"),
                    ("need_more", "Requesting More Funds"),
                    ("rejected", "Rejected"),
                    ("declined", "Declined"),
                    ("accepted", "Accepted"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TravelGrantMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=False,
                        help_text="Whether message is visible to the applicant.",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="program_programs.travelgrant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted the message.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
