# Generated by Django 5.2.11 on 2026-02-12 04:49

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_programs", "0004_travel_grant_pycon_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelgrant",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("general", "General Applicant"),
                    ("staff", "Conference Staff/Volunteer"),
                    ("speaker", "Speaker"),
                    ("core_dev", "Core Developer"),
                    ("psf_board", "PSF Board Member"),
                    ("community", "Outstanding Community Member"),
                    ("education", "Education"),
                    ("pyladies", "PyLadies"),
                    ("other", "Other"),
                ],
                default="general",
                help_text="Application classification.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("zelle", "Zelle"),
                            ("paypal", "PayPal"),
                            ("ach", "ACH (Direct Deposit)"),
                            ("wire", "Wire Transfer"),
                            ("wise", "Wise"),
                            ("check", "Check"),
                        ],
                        max_length=20,
                    ),
                ),
                ("legal_name", models.CharField(max_length=500)),
                ("address_street", models.CharField(max_length=512)),
                ("address_city", models.CharField(max_length=256)),
                (
                    "address_state",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("address_zip", models.CharField(max_length=64)),
                ("address_country", models.CharField(max_length=256)),
                (
                    "paypal_email",
                    encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=500, null=True),
                ),
                (
                    "zelle_email",
                    encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=500, null=True),
                ),
                (
                    "wise_email",
                    encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=500, null=True),
                ),
                (
                    "bank_name",
                    encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=256, null=True),
                ),
                (
                    "bank_account_number",
                    encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=128, null=True),
                ),
                (
                    "bank_routing_number",
                    encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=128, null=True),
                ),
                (
                    "bank_holder_name",
                    encrypted_fields.fields.EncryptedCharField(blank=True, default=None, max_length=512, null=True),
                ),
                (
                    "bank_holder_address",
                    encrypted_fields.fields.EncryptedTextField(blank=True, default=None, null=True),
                ),
                (
                    "bank_address",
                    encrypted_fields.fields.EncryptedTextField(blank=True, default=None, null=True),
                ),
                (
                    "bank_additional",
                    encrypted_fields.fields.EncryptedTextField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_info",
                        to="program_programs.travelgrant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "payment info",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_type",
                    models.CharField(
                        choices=[("airfare", "Airfare"), ("lodging", "Lodging")],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "receipt_file",
                    models.FileField(
                        upload_to="travel_grant_receipts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("flagged", models.BooleanField(default=False)),
                (
                    "flagged_reason",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("flagged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flagged_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="program_programs.travelgrant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("review_receipt", "Can review travel grant receipts")],
            },
        ),
    ]
