# Generated by Django 5.2.11 on 2026-02-12 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "program_programs",
            "0005_alter_travelgrant_application_type_paymentinfo_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="travelgrant",
            name="disbursed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual amount disbursed to the grantee.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="disbursed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelgrant",
            name="disbursed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disbursed_grants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="travelgrant",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("info_needed", "Information Needed"),
                    ("offered", "Offered"),
                    ("need_more", "Requesting More Funds"),
                    ("rejected", "Rejected"),
                    ("declined", "Declined"),
                    ("accepted", "Accepted"),
                    ("disbursed", "Disbursed"),
                ],
                default="submitted",
                max_length=20,
            ),
        ),
    ]
