# Generated by Django 5.2.11 on 2026-02-12 05:07

import django.core.validators
from django.db import migrations, models

import django_program.programs.models


class Migration(migrations.Migration):
    dependencies = [
        ("program_programs", "0006_travelgrant_disbursed_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_file",
            field=models.FileField(
                upload_to=django_program.programs.models.receipt_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "jpg", "jpeg", "png"])
                ],
            ),
        ),
    ]
