# Generated by Django 5.2.11 on 2026-02-13 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_programs", "0007_alter_receipt_receipt_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activitysignup",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="activitysignup",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitysignup",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("waitlisted", "Waitlisted"),
                    ("cancelled", "Cancelled"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="activitysignup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("activity", "user"),
                name="unique_active_signup_per_user",
            ),
        ),
    ]
