# Generated by Django 5.2.11 on 2026-02-13 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program_programs", "0008_alter_activitysignup_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["start_time", "name"],
                "permissions": [("manage_activity", "Can manage activity signups")],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="organizers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can manage signups for this activity.",
                related_name="organized_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
